// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: test

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 80);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_x(ui_Button2, -9);
    lv_obj_set_y(ui_Button2, -31);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -11);
    lv_obj_set_y(ui_Label3, -30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "切换");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_ALIBABA16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconHeadset = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_iconHeadset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconHeadset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconHeadset, -11);
    lv_obj_set_y(ui_iconHeadset, -73);
    lv_obj_set_align(ui_iconHeadset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconHeadset, "");
    lv_obj_set_style_text_color(ui_iconHeadset, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconHeadset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconHeadset, &ui_font_iconfont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBadminton = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_iconBadminton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconBadminton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconBadminton, -69);
    lv_obj_set_y(ui_iconBadminton, 43);
    lv_obj_set_align(ui_iconBadminton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconBadminton, "");
    lv_obj_set_style_text_color(ui_iconBadminton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconBadminton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconBadminton, &ui_font_iconfont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBattledore = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_iconBattledore, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconBattledore, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconBattledore, -87);
    lv_obj_set_y(ui_iconBattledore, 69);
    lv_obj_set_align(ui_iconBattledore, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconBattledore, "");
    lv_obj_set_style_text_color(ui_iconBattledore, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconBattledore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconBattledore, &ui_font_iconfont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 21);
    lv_obj_set_y(ui_Switch2, 54);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
