// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
extern lv_obj_t * ui_HomePage;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_iconHeart;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_ALIBABA16);
LV_FONT_DECLARE(ui_font_ALIBABA32);
LV_FONT_DECLARE(ui_font_iconfont32);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
