// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: test

#include "../ui.h"

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -7);
    lv_obj_set_y(ui_Label2, 10);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "你好");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_ALIBABA16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -7);
    lv_obj_set_y(ui_Label1, 45);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "你好");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_ALIBABA32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconHeart = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_iconHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconHeart, 0);
    lv_obj_set_y(ui_iconHeart, -19);
    lv_obj_set_align(ui_iconHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconHeart, "");
    lv_obj_set_style_text_color(ui_iconHeart, lv_color_hex(0xC6232A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconHeart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconHeart, &ui_font_iconfont32, LV_PART_MAIN | LV_STATE_DEFAULT);

}
