// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: test

#include "../ui.h"

// 初始化屏幕1
void ui_Screen1_screen_init(void)
{
    // 创建一个新的屏幕对象 ui_Screen1，作为整个屏幕的容器
    ui_Screen1 = lv_obj_create(NULL);
    /* lv_obj_clear_flag()：这是 LVGL 中的一个函数，用来清除指定对象的某个标志位。
    LV_OBJ_FLAG_SCROLLABLE：这是一个标志位，表示该对象具有滚动能力。如果启用该标志，表示该对象可以在显示区域内滚动其内容。
    所以，lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE) 实际上是告诉 LVGL：ui_Screen1 不允许滚动，即这个屏幕容器不能在其中的控件内容溢出时进行滚动。 
    */
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // 创建一个标签控件 ui_iconHeart，用于显示图标
    ui_iconHeart = lv_label_create(ui_Screen1);
    /* lv_obj_set_width(ui_iconHeart, LV_SIZE_CONTENT); 这行代码的意思是：
    让 ui_iconHeart（在这个代码中是一个标签控件）自动根据其显示内容的宽度来设置宽度。
    例如，ui_iconHeart 显示的是一个图标（使用 Unicode 字符），这个字符的实际宽度将决定该标签控件的宽度。 
    */
    lv_obj_set_width(ui_iconHeart, LV_SIZE_CONTENT); /// 1
    // 设置图标标签的高度为内容的高度
    lv_obj_set_height(ui_iconHeart, LV_SIZE_CONTENT); /// 1
    // 设置图标标签的位置（相对于父容器 ui_Screen1）
    lv_obj_set_x(ui_iconHeart, 2);   // 设置 X 坐标
    lv_obj_set_y(ui_iconHeart, -95); // 设置 Y 坐标
    // 设置图标标签的对齐方式为中心对齐
    lv_obj_set_align(ui_iconHeart, LV_ALIGN_CENTER);
    // 设置标签的文本为 Unicode 图标字符
    lv_label_set_text(ui_iconHeart, "");
    // 设置标签文本的颜色为红色（使用 hex 颜色代码）
    /* LV_PART_MAIN | LV_STATE_DEFAULT：
    LV_PART_MAIN：表示应用于控件的主要部分。比如对于标签控件，就是标签文本本身。
    LV_STATE_DEFAULT：表示控件的默认状态（例如普通状态，没有被点击或悬停）。
    通过 LV_PART_MAIN | LV_STATE_DEFAULT，你可以确保该样式应用于控件的默认状态下（一般情况下，控件都是默认状态）。
    */
    lv_obj_set_style_text_color(ui_iconHeart, lv_color_hex(0xAE142D), LV_PART_MAIN | LV_STATE_DEFAULT);
    // 设置文本的不透明度为完全不透明（255）
    lv_obj_set_style_text_opa(ui_iconHeart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // 设置文本的字体为自定义图标字体（大小为32）
    lv_obj_set_style_text_font(ui_iconHeart, &ui_font_iconfont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建一个虚拟键盘控件 ui_Keyboard2，并将其添加到屏幕 ui_Screen1 中
    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    // 设置键盘控件的宽度为 204 像素
    lv_obj_set_width(ui_Keyboard2, 204);
    // 设置键盘控件的高度为 120 像素
    lv_obj_set_height(ui_Keyboard2, 120);
    // 设置键盘的位置
    lv_obj_set_x(ui_Keyboard2, 2);  // 设置 X 坐标
    lv_obj_set_y(ui_Keyboard2, 70); // 设置 Y 坐标
    // 设置键盘的对齐方式为父容器 ui_Screen1 的中心对齐
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    // 创建一个标签控件 ui_Label1，用于显示文本 "你好"
    ui_Label1 = lv_label_create(ui_Screen1);
    // 设置标签的宽度为内容的宽度
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT); /// 1
    // 设置标签的高度为内容的高度
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    // 设置标签的位置
    lv_obj_set_x(ui_Label1, 3);   // 设置 X 坐标
    lv_obj_set_y(ui_Label1, -65); // 设置 Y 坐标
    // 设置标签的对齐方式为父容器 ui_Screen1 的中心对齐
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    // 设置标签的文本内容为 "你好"
    lv_label_set_text(ui_Label1, "你好");
    // 设置标签文本的颜色为蓝色（使用 hex 颜色代码）
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x283199), LV_PART_MAIN | LV_STATE_DEFAULT);
    // 设置文本的不透明度为完全不透明（255）
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // 设置标签的字体为阿里巴巴普惠体16px字体
    lv_obj_set_style_text_font(ui_Label1, &ui_font_ALIBABA16, LV_PART_MAIN | LV_STATE_DEFAULT);
}
