// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: test

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iconHeart = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_iconHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconHeart, 2);
    lv_obj_set_y(ui_iconHeart, -95);
    lv_obj_set_align(ui_iconHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconHeart, "");
    lv_obj_set_style_text_color(ui_iconHeart, lv_color_hex(0xAE142D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconHeart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconHeart, &ui_font_iconfont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard2, 204);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 2);
    lv_obj_set_y(ui_Keyboard2, 70);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 3);
    lv_obj_set_y(ui_Label1, -65);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "你好");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x283199), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_ALIBABA16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
