// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_iconHeart;
extern lv_obj_t * ui_Label1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_iconHeadset;
extern lv_obj_t * ui_iconBadminton;
extern lv_obj_t * ui_iconBattledore;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_ALIBABA16);
LV_FONT_DECLARE(ui_font_ALIBABA32);
LV_FONT_DECLARE(ui_font_iconfont32);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
